-- Run once in Supabase Dashboard > SQL Editor.
-- Public reads are intentional for the public streetlight map. Writes should be
-- tightened to authenticated users after Supabase Auth replaces the legacy login.

create table if not exists public.streetlights (
  id text primary key,
  latitude double precision not null,
  longitude double precision not null,
  village_code text,
  village_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.repair_reports (
  id bigint generated by default as identity primary key,
  streetlight_id text not null,
  reported_at timestamptz not null default now(),
  fault text not null default '',
  status text not null default '未查修',
  repaired_at timestamptz,
  note text,
  reporter_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.replacement_history (
  id bigint generated by default as identity primary key,
  streetlight_id text not null,
  old_latitude double precision,
  old_longitude double precision,
  new_latitude double precision,
  new_longitude double precision,
  action text not null,
  note text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.base_surveys (
  id bigint generated by default as identity primary key,
  streetlight_id text not null,
  surveyed_at timestamptz not null default now(),
  latitude double precision,
  longitude double precision,
  before_photo_url text,
  after_photo_url text,
  created_at timestamptz not null default now()
);

create index if not exists repair_reports_streetlight_status_idx
  on public.repair_reports (streetlight_id, status);
create index if not exists replacement_history_created_idx
  on public.replacement_history (created_at desc);

alter table public.streetlights enable row level security;
alter table public.repair_reports enable row level security;
alter table public.replacement_history enable row level security;
alter table public.base_surveys enable row level security;

drop policy if exists "public read streetlights" on public.streetlights;
create policy "public read streetlights" on public.streetlights for select to anon, authenticated using (true);
drop policy if exists "public read repair reports" on public.repair_reports;
create policy "public read repair reports" on public.repair_reports for select to anon, authenticated using (true);
drop policy if exists "public read replacement history" on public.replacement_history;
create policy "public read replacement history" on public.replacement_history for select to anon, authenticated using (true);

-- Temporary migration policies. Replace anon writes with authenticated-only
-- policies after Supabase Auth is enabled.
drop policy if exists "temporary insert repair reports" on public.repair_reports;
create policy "temporary insert repair reports" on public.repair_reports for insert to anon, authenticated with check (true);
drop policy if exists "temporary update repair reports" on public.repair_reports;
create policy "temporary update repair reports" on public.repair_reports for update to anon, authenticated using (true) with check (true);
drop policy if exists "temporary write streetlights" on public.streetlights;
create policy "temporary write streetlights" on public.streetlights for all to anon, authenticated using (true) with check (true);
drop policy if exists "temporary write replacement history" on public.replacement_history;
create policy "temporary write replacement history" on public.replacement_history for all to anon, authenticated using (true) with check (true);
drop policy if exists "temporary write base surveys" on public.base_surveys;
create policy "temporary write base surveys" on public.base_surveys for insert to anon, authenticated with check (true);

-- Temporary permissions required by the browser-based database manager.
-- Replace these with authenticated admin policies before public production use.
drop policy if exists "temporary delete repair reports" on public.repair_reports;
create policy "temporary delete repair reports" on public.repair_reports for delete to anon, authenticated using (true);
drop policy if exists "temporary read base surveys" on public.base_surveys;
create policy "temporary read base surveys" on public.base_surveys for select to anon, authenticated using (true);
drop policy if exists "temporary update base surveys" on public.base_surveys;
create policy "temporary update base surveys" on public.base_surveys for update to anon, authenticated using (true) with check (true);
drop policy if exists "temporary delete base surveys" on public.base_surveys;
create policy "temporary delete base surveys" on public.base_surveys for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, public)
values ('streetlight-photos', 'streetlight-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "public read streetlight photos" on storage.objects;

-- Private canonical storage; browser writes require a signed PUT URL.
insert into storage.buckets (id, name, public)
values ('case-photos', 'case-photos', false)
on conflict (id) do update set public = false;

create table if not exists public.photo_sync_settings (
  singleton boolean primary key default true check (singleton),
  google_drive_backup_enabled boolean not null default false
);
insert into public.photo_sync_settings (singleton, google_drive_backup_enabled)
values (true, false) on conflict (singleton) do nothing;
create policy "public read streetlight photos" on storage.objects for select to public using (bucket_id = 'streetlight-photos');
drop policy if exists "temporary upload streetlight photos" on storage.objects;
create policy "temporary upload streetlight photos" on storage.objects for insert to anon, authenticated with check (bucket_id = 'streetlight-photos');

-- Photo hand-off queue. A trigger creates a job after the browser has safely
-- uploaded a temporary object; the Edge Function moves it to Google Drive.
create table if not exists public.photo_transfers (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  destination text not null check (destination in ('base-survey', 'replacement', 'repair')),
  record_id bigint not null,
  slot text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'drive_uploaded', 'failed', 'completed')),
  attempts integer not null default 0,
  last_error text,
  drive_file_id text,
  drive_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists photo_transfers_ready_idx on public.photo_transfers (status, created_at);

alter table public.photo_transfers enable row level security;
-- Jobs are created only by the storage trigger and handled using the Edge
-- Function service key; browsers must not be able to read or alter this queue.

-- Trigger an asynchronous attempt immediately after each accepted upload.  The
-- once-per-minute Cron job remains the durable retry path for failed jobs.
create or replace function public.request_photo_drive_sync()
returns void language plpgsql security definer set search_path = public, net, vault as $$
begin
  perform net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name = 'photo_sync_project_url') || '/functions/v1/photo-drive-sync',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-photo-sync-secret',
      (select decrypted_secret from vault.decrypted_secrets where name = 'photo_sync_cron_secret')),
    body := '{}'::jsonb,
    timeout_milliseconds := 55000
  );
exception when others then
  raise warning 'Could not start immediate photo sync: %', sqlerrm;
end $$;

create or replace function public.queue_streetlight_photo()
returns trigger language plpgsql security definer set search_path = public as $$
declare m text[]; target_record_id bigint; target_destination text; target_slot text;
begin
  if new.bucket_id <> 'streetlight-photos' then return new; end if;
  m := regexp_match(new.name, '^repair-reports/(.+)_(before|after)[.][^/]+$');
  if m is not null then
    select id into target_record_id from repair_reports where streetlight_id = m[1]
    order by repaired_at desc nulls last, id desc limit 1;
    target_destination := 'repair'; target_slot := case when m[2] = 'before' then '0-pre' else '0-post' end;
  else
    m := regexp_match(new.name, '^base-surveys/(.+)_(before|after)[.][^/]+$');
    if m is not null then
      select id into target_record_id from base_surveys where streetlight_id = m[1]
      order by created_at desc, id desc limit 1;
      target_destination := 'base-survey'; target_slot := case when m[2] = 'before' then 'before' else 'after' end;
    else return new;
    end if;
  end if;
  if target_record_id is null then raise warning 'No record found for uploaded photo %', new.name; return new; end if;
  insert into photo_transfers(storage_path, destination, record_id, slot)
  values (new.name, target_destination, target_record_id, target_slot)
  on conflict (storage_path) do update set destination = excluded.destination, record_id = excluded.record_id,
    slot = excluded.slot, status = 'pending', attempts = 0, last_error = null, drive_file_id = null,
    drive_url = null, completed_at = null, updated_at = now();
  perform public.request_photo_drive_sync();
  return new;
end $$;
drop trigger if exists queue_streetlight_photo_after_upload on storage.objects;
create trigger queue_streetlight_photo_after_upload after insert or update on storage.objects
for each row execute function public.queue_streetlight_photo();

create or replace function public.claim_photo_transfers(batch_size integer default 10)
returns setof public.photo_transfers language sql security definer set search_path = public as $$
  with candidates as (
    select id from photo_transfers
    where status in ('pending', 'failed', 'drive_uploaded')
       or (status = 'processing' and updated_at < now() - interval '10 minutes')
    order by created_at for update skip locked limit greatest(1, least(batch_size, 25))
  ), claimed as (
    update photo_transfers p set status = case when p.status = 'drive_uploaded' then 'drive_uploaded' else 'processing' end, attempts = attempts + 1,
      updated_at = now(), last_error = null
    from candidates c where p.id = c.id returning p.*
  ) select * from claimed;
$$;

create or replace function public.finish_photo_transfer(job_id bigint, file_id text, file_url text)
returns void language plpgsql security definer set search_path = public as $$
declare job photo_transfers;
declare photo_index integer;
begin
  select * into job from photo_transfers where id = job_id for update;
  if not found then raise exception 'Photo job % not found', job_id; end if;
  if job.destination = 'base-survey' then
    update base_surveys set before_photo_url = case when job.slot = 'before' then file_url else before_photo_url end,
      after_photo_url = case when job.slot = 'after' then file_url else after_photo_url end where id = job.record_id;
  elsif job.destination = 'replacement' then
    update replacement_history set photo_url = file_url where id = job.record_id;
  else
    photo_index := (regexp_match(job.slot, '^([0-9]+)-(pre|post)$'))[1]::integer * 2
      + case when job.slot like '%-post' then 1 else 0 end;
    update repair_reports set metadata = jsonb_set(metadata, array['photos', photo_index::text], to_jsonb(file_url), true)
      where id = job.record_id;
  end if;
  update photo_transfers set status = 'completed', drive_file_id = file_id, drive_url = file_url,
    completed_at = now(), updated_at = now(), last_error = null where id = job_id;
end $$;

create or replace function public.record_drive_upload(job_id bigint, file_id text, file_url text)
returns void language sql security definer set search_path = public as $$
  update photo_transfers set status = 'drive_uploaded', drive_file_id = file_id, drive_url = file_url,
    updated_at = now(), last_error = null where id = job_id;
$$;

create or replace function public.fail_photo_transfer(job_id bigint, error_message text)
returns void language sql security definer set search_path = public as $$
  update photo_transfers set status = case when drive_file_id is not null then 'drive_uploaded' else 'failed' end,
    last_error = left(error_message, 2000), updated_at = now()
  where id = job_id;
$$;
