-- Run once in Supabase Dashboard > SQL Editor.
-- Public reads are intentional for the public streetlight map. Writes should be
-- tightened to authenticated users after Supabase Auth replaces the legacy login.

create table if not exists public.streetlights (
  id text primary key,
  latitude double precision not null,
  longitude double precision not null,
  village_code text,
  village_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.repair_reports (
  id bigint generated by default as identity primary key,
  streetlight_id text not null,
  reported_at timestamptz not null default now(),
  fault text not null default '',
  status text not null default '未查修',
  repaired_at timestamptz,
  note text,
  reporter_name text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.replacement_history (
  id bigint generated by default as identity primary key,
  streetlight_id text not null,
  old_latitude double precision,
  old_longitude double precision,
  new_latitude double precision,
  new_longitude double precision,
  action text not null,
  note text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.base_surveys (
  id bigint generated by default as identity primary key,
  streetlight_id text not null,
  surveyed_at timestamptz not null default now(),
  latitude double precision,
  longitude double precision,
  before_photo_url text,
  after_photo_url text,
  created_at timestamptz not null default now()
);

create index if not exists repair_reports_streetlight_status_idx
  on public.repair_reports (streetlight_id, status);
create index if not exists replacement_history_created_idx
  on public.replacement_history (created_at desc);

alter table public.streetlights enable row level security;
alter table public.repair_reports enable row level security;
alter table public.replacement_history enable row level security;
alter table public.base_surveys enable row level security;

drop policy if exists "public read streetlights" on public.streetlights;
create policy "public read streetlights" on public.streetlights for select to anon, authenticated using (true);
drop policy if exists "public read repair reports" on public.repair_reports;
create policy "public read repair reports" on public.repair_reports for select to anon, authenticated using (true);
drop policy if exists "public read replacement history" on public.replacement_history;
create policy "public read replacement history" on public.replacement_history for select to anon, authenticated using (true);

-- Temporary migration policies. Replace anon writes with authenticated-only
-- policies after Supabase Auth is enabled.
drop policy if exists "temporary insert repair reports" on public.repair_reports;
create policy "temporary insert repair reports" on public.repair_reports for insert to anon, authenticated with check (true);
drop policy if exists "temporary update repair reports" on public.repair_reports;
create policy "temporary update repair reports" on public.repair_reports for update to anon, authenticated using (true) with check (true);
drop policy if exists "temporary write streetlights" on public.streetlights;
create policy "temporary write streetlights" on public.streetlights for all to anon, authenticated using (true) with check (true);
drop policy if exists "temporary write replacement history" on public.replacement_history;
create policy "temporary write replacement history" on public.replacement_history for all to anon, authenticated using (true) with check (true);
drop policy if exists "temporary write base surveys" on public.base_surveys;
create policy "temporary write base surveys" on public.base_surveys for insert to anon, authenticated with check (true);

insert into storage.buckets (id, name, public)
values ('streetlight-photos', 'streetlight-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "public read streetlight photos" on storage.objects;
create policy "public read streetlight photos" on storage.objects for select to public using (bucket_id = 'streetlight-photos');
drop policy if exists "temporary upload streetlight photos" on storage.objects;
create policy "temporary upload streetlight photos" on storage.objects for insert to anon, authenticated with check (bucket_id = 'streetlight-photos');

